org: jpweijers
app: odoo-clockify-sync
service: odoo-clockify-sync

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  region: eu-west-1
  runtime: python3.8
  lambdaHashingVersion: 20201221
  timeout: 30
  memorySize: 128
  environment:
    ODOO_URL: ${env:ODOO_URL}
    ODOO_LOGIN: ${env:ODOO_LOGIN}
    ODOO_PASSWORD: ${env:ODOO_PASSWORD}
    CLOCKIFY_URL: ${env:CLOCKIFY_URL}
    CLOCKIFY_KEY: ${env:CLOCKIFY_KEY}
    CLOCKIFY_WORKSPACE: ${env:CLOCKIFY_WORKSPACE}
    CLOCKIFY_USER: ${env:CLOCKIFY_USER}
    CLOCKIFY_CLIENT_ID: ${env:CLOCKIFY_CLIENT_ID}
  layers:
    - { Ref: PythonRequirementsLambdaLayer }

functions:
  sync-projects:
    timeout: 60
    handler: functions/projects_sync.handler

  webhook-stopped:
    handler: src/functions/webhook/handler.updated
    events:
      - httpApi:
          path: /clockify/webhook/stopped
          method: post
    environment:
      CLOCKIFY_WEBHOOK_SIGNATURE_STOPPED: ${env:CLOCKIFY_WEBHOOK_SIGNATURE_STOPPED}

  webhook-deleted:
    handler: src/functions/webhook/handler.deleted
    events:
      - httpApi:
          path: /clockify/webhook/deleted
          method: post
    environment:
      CLOCKIFY_WEBHOOK_SIGNATURE_DELETED: ${env:CLOCKIFY_WEBHOOK_SIGNATURE_DELETED}

  webhook-manual:
    handler: src/functions/webhook/handler.manual
    events:
      - httpApi:
          path: /clockify/webhook/manual
          method: post
    environment:
      CLOCKIFY_WEBHOOK_SIGNATURE_MANUAL: ${env:CLOCKIFY_WEBHOOK_SIGNATURE_MANUAL}

  webhook-updated:
    handler: src/functions/webhook/handler.updated
    events:
      - httpApi:
          path: /clockify/webhook/updated
          method: post
    environment:
      CLOCKIFY_WEBHOOK_SIGNATURE_UPDATED: ${env:CLOCKIFY_WEBHOOK_SIGNATURE_UPDATED}

package:
  individually: true
  exclude:
    - ./**
  include:
    - src/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    layer: true
