name: test-action
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - run: pip install poetry
      - run: poetry install
      - run: poetry shell
  test:
    needs: setup
    steps:
      - run: pytest
